# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

exclude:
 - "/vendor/"

# Site settings
title: Polyphant
subtitle: "Technology, Astronomy and other random noise, from an Astrophysicist in London"
email: chrisl1991@hotmail.co.uk
name: Christopher Lovell
description: >
  Technology, Astronomy and other random noise, from an Astrophysicist in London
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://bencentra.github.io" # the base hostname & protocol for your site
cover: "/images/hdf.gif"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 8
paginate_path: "/page:num/"
inter_post_navigation: true

# Disqus comments
disqus_shortname: polyphant

# Google analytics
ga_tracking_id: "UA-61827184-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: polyphantastic
    url: https://twitter.com/polyphantastic
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: Polyphant
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: polyphant1
    url: https://github.com/polyphant1
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: 
    url:
    desc: Connect with me on LinkedIn
    share: false

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: true

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/polyphant1/polyphant1.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:polyphant1/polyphant1.github.io"
